on:
  release:
    types: [published]

name: Publish

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - run: cargo login ${{secrets.CARGO_TOKEN}}
      - run: cargo publish --manifest-path sqlxmq_macros/Cargo.toml
      - name: Wait for crates.io to update
        run: sleep 30
      - run: cargo publish --manifest-path Cargo.toml
